# Generated by Django 5.2.8 on 2025-11-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-vote_count', 'title']},
        ),
        migrations.AddField(
            model_name='movie',
            name='showed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
