# Generated by Django 5.2.8 on 2025-12-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0003_alter_movie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_url',
            field=models.URLField(default='/static/showtimes/images/no-cover.jpg'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
